---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Steven Li
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(dplyr)
library(knitr)
```


# Introduction

# Data {#sec-data}
```{r}
#| echo: false
#| warning: false
#| message: false

bikeShare_data <- read_csv(here::here(
  "data/analysis_data/cleaned_bikeshare_data.csv"))

bikeWay_data <- read_csv(here::here("data/analysis_data/bikeway_data.csv"))
```

```{r}
#| label: fig-sample_bikeshare
#| title: Sample of Toronto's Bike Share Ridership Data
#| echo: false
#| warning: false
#| message: false

bikeShare_sample <- bikeShare_data %>% sample_n(5) %>% as_tibble()

colnames(bikeShare_sample) <- c("Trip ID", "Date")

kable(bikeShare_sample)
```


```{r}
#| label: fig-sample_bikeway
#| title: Sample of Toronto's Cycling Network Data
#| echo: false
#| warning: false
#| message: false

bikeWay_sample <- bikeWay_data %>% sample_n(5) %>% as_tibble()

colnames(bikeWay_sample) <- c("Trip ID", "Date")

kable(bikeWay_sample)
```


```{r}
#| label: fig-yearly_ridership
#| title: Yearly Bike Share Ridership
#| echo: false
#| warning: false
#| message: false

yearly_bike_share_usage <- bikeShare_data %>%
  mutate(year = year(ymd(start_date))) %>%
  group_by(year) %>%
  summarise(total_rides = n())

kable(yearly_bike_share_usage)
```


# Results


# Discussion

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps

\newpage

\appendix

# Appendix {-}


# Additional data details


## Diagnostics

\newpage


# References


